
name: Firefox Package Builder

on:
  push:
    tags:
      - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        # 1. Package the extension as standard ZIP file (AMO requires ZIP for submission)
        - name: Create Firefox package (zip)
          run: |
            ZIP_NAME=contribution-graph-realignment-tool-${{ github.ref_name }}.zip
            cd extension
            zip -r ../$ZIP_NAME .
            echo "ZIP_FILE_NAME=$ZIP_NAME" >> $GITHUB_ENV

        # 2. Create the GitHub release and attach the ZIP file
        - name: Create GitHub Release
          uses: softprops/action-gh-release@v1
          with:
            files: ${{ env.ZIP_FILE_NAME }}
            name: Firefox Extension ${{ github.ref_name }}
            draft: false
            prerelease: false
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Delete Default Source Code Archives
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            # The tag name (e.g., v1.0.0) is needed to target the correct Release
            TAG_NAME=${{ github.ref_name }}
            
            echo "Searching for default source archives to delete for tag $TAG_NAME..."
          
            # Use 'gh' to find assets matching the default source code archive patterns
            # and pipe their IDs to the delete command.
            gh release delete-asset "$TAG_NAME" "source.zip" --yes || echo "source.zip not found, continuing..."
            gh release delete-asset "$TAG_NAME" "source.tar.gz" --yes || echo "source.tar.gz not found, continuing..."

            echo "Cleanup complete."
