
name: Firefox Package Builder

on:
  push:
    tags:
      - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        # 1. Package the extension as standard ZIP file (AMO requires ZIP for submission)
        - name: Create Firefox package (zip)
          run: |
            ZIP_NAME=contribution-graph-realignment-tool-${{ github.ref_name }}.zip
            cd extension
            zip -r ../$ZIP_NAME .
            echo "ZIP_FILE_NAME=$ZIP_NAME" >> $GITHUB_ENV

        # 2. Create the GitHub release and attach the ZIP file
        - name: Create GitHub Release
          uses: softprops/action-gh-release@v1
          with:
            files: ${{ env.ZIP_FILE_NAME }}
            name: Firefox Extension ${{ github.ref_name }}
            draft: false
            prerelease: false
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Delete Default Source Code Archives
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            # Use GitHub CLI to display all assets for the release
            gh release view ${{ github.ref_name }} --json assets --template '{{ range .assets }}{{ .name }}\n{{ end }}'

            # The tag name (e.g., v1.0.0) is needed to target the correct Release
            TAG=${{ github.ref_name }}
            echo "Tag Name: $TAG"

            # Construct the source archive names
            SOURCE_ZIP="${TAG}.zip"
            SOURCE_TAR_GZ="${TAG}.tar.gz"
            echo "Source ZIP: $SOURCE_ZIP"
            echo "Source TAR.GZ: $SOURCE_TAR_GZ"

            echo "Attempting to delete default source archives from release..."

            gh release delete-asset "$TAG_NAME" "$SOURCE_ZIP" --yes || echo "$SOURCE_ZIP not found, continuing..."
            gh release delete-asset "$TAG_NAME" "$SOURCE_TAR_GZ" --yes || echo "$SOURCE_TAR_GZ not found, continuing..."

            echo "Cleanup complete."
