
name: Firefox Package Builder

on:
  push:
    tags:
      - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Package extension as XPI
          run: |
            cd extension
            zip -r ../contribution-graph-realignment-tool.xpi .

        # 1. Package the extension as standard ZIP file (AMO requires ZIP for submission)
        - name: Create Firefox package (zip)
          run: |
            ZIP_NAME=contribution-graph-realignment-tool-${{ github.ref_name }}.zip
            cd extension
            zip -r ../$ZIP_NAME .
            echo "ZIP_FILE_NAME=$ZIP_NAME" >> $GITHUB_ENV

        # 2. Create the GitHub release and attach the ZIP file
        - name: Create GitHub Release
          uses: softprops/action-gh-release@v1
          with:
            files: ${{ env.ZIP_FILE_NAME }}
            draft: false
            prerelease: false
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
